In [1]:
import pandas as pd

In [2]:
# read csv file
penguins = pd.read_csv("penguins.csv")

In [3]:
# head
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [4]:
# tail 
penguins.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [5]:
# see dataframe dimension
penguins.shape

(344, 7)

In [6]:
# penguins info
penguins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [7]:
# summary statistics
penguins.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [8]:
# remove rows with missing values
clean_penguins = penguins.dropna()
clean_penguins.shape

(333, 7)

In [9]:
# check number of null values in each column
clean_penguins.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [10]:
# select a single column
clean_penguins['species']

0      Adelie
1      Adelie
2      Adelie
4      Adelie
5      Adelie
        ...
338    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, Length: 333, dtype: object

In [11]:
# select more than one column
clean_penguins[['species', 'island', 'sex']].head()

  species     island     sex
0  Adelie  Torgersen    MALE
1  Adelie  Torgersen  FEMALE
2  Adelie  Torgersen  FEMALE
4  Adelie  Torgersen  FEMALE
5  Adelie  Torgersen    MALE

In [12]:
# rename column sex to gender
clean_penguins = clean_penguins.rename(columns = {'sex': 'gender'})
clean_penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,gender
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE

In [13]:
# drop columns 
small_penguins = clean_penguins.drop(columns = ['gender', 'body_mass_g', 'island'])
small_penguins.head()

  species  bill_length_mm  bill_depth_mm  flipper_length_mm
0  Adelie            39.1           18.7              181.0
1  Adelie            39.5           17.4              186.0
2  Adelie            40.3           18.0              195.0
4  Adelie            36.7           19.3              193.0
5  Adelie            39.3           20.6              190.0

In [14]:
# iloc slice rows 0:5
small_penguins.iloc[0:5]

  species  bill_length_mm  bill_depth_mm  flipper_length_mm
0  Adelie            39.1           18.7              181.0
1  Adelie            39.5           17.4              186.0
2  Adelie            40.3           18.0              195.0
4  Adelie            36.7           19.3              193.0
5  Adelie            39.3           20.6              190.0

In [15]:
# loc filter rows with condition
small_penguins.loc[ small_penguins['bill_length_mm'] >= 55 ]

       species  bill_length_mm  bill_depth_mm  flipper_length_mm
169  Chinstrap            58.0           17.8              181.0
215  Chinstrap            55.8           19.8              207.0
253     Gentoo            59.6           17.0              230.0
321     Gentoo            55.9           17.0              228.0
335     Gentoo            55.1           16.0              230.0

In [16]:
# query same result
small_penguins.query( "bill_length_mm >= 55" )

       species  bill_length_mm  bill_depth_mm  flipper_length_mm
169  Chinstrap            58.0           17.8              181.0
215  Chinstrap            55.8           19.8              207.0
253     Gentoo            59.6           17.0              230.0
321     Gentoo            55.9           17.0              228.0
335     Gentoo            55.1           16.0              230.0

In [17]:
# sort values descending order (high to low)
small_penguins.sort_values(by = 'bill_length_mm', ascending = False)

       species  bill_length_mm  bill_depth_mm  flipper_length_mm
253     Gentoo            59.6           17.0              230.0
169  Chinstrap            58.0           17.8              181.0
321     Gentoo            55.9           17.0              228.0
215  Chinstrap            55.8           19.8              207.0
335     Gentoo            55.1           16.0              230.0
..         ...             ...            ...                ...
18      Adelie            34.4           18.4              184.0
92      Adelie            34.0           17.1              185.0
70      Adelie            33.5           19.0              190.0
98      Adelie            33.1           16.1              178.0
142     Adelie            32.1           15.5              188.0

[333 rows x 4 columns]

In [18]:
# write csv file
small_penguins.to_csv("small_penguins.csv")